export const OBTENER_ARTICULOS = 'OBTENER_ARTICULOS'
export const OBTENER_ARTICULOS_ERROR = 'OBTENER_ARTICULOS_ERROR'
export const OBTENER_ARTICULOS_EXITO = 'OBTENER_ARTICULOS_EXITO'

export const OBTENER_ARTICULOS_ARTISTA = 'OBTENER_ARTICULOS_ARTISTA'
export const OBTENER_ARTICULOS_ARTISTA_ERROR = 'OBTENER_ARTICULOS_ARTISTA_ERROR'
export const OBTENER_ARTICULOS_ARTISTA_EXITO = 'OBTENER_ARTICULOS_ARTISTA_EXITO'

export const ARTISTA_SELECCIONADO = 'ARTISTA_SELECCIONADO'
export const ARTISTA_SELECCIONADO_ERROR = 'ARTISTA_SELECCIONADO_ERROR'
export const ARTISTA_SELECCIONADO_EXITO = 'ARTISTA_SELECCIONADO_EXITO'